# Generated by Django 5.2 on 2025-05-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department_id",
            field=models.CharField(max_length=100),
        ),
    ]
