# Generated by Django 5.2 on 2025-05-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_department_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="department_id",
            new_name="department_name",
        ),
    ]
