version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
    - "8000:8000"
    working_dir: /app
    command: gunicorn --bind 0.0.0.0:8000 hrms_backend.wsgi:application
    volumes:
    - ./backend:/app  # <- 이 부분이 backend 폴더를 /app으로 마운트
    environment:
    - DEBUG=1
    - DB_HOST=db
    - DB_NAME=hrms
    - DB_USER=root
    - DB_PASS=password
    depends_on:
    - db

  frontend: 
    build:
      context: ./frontend
      
    ports:
    - "3000:3000"
    working_dir: /app
    command: npm run dev
    volumes:
    - ./frontend:/app
    depends_on:
    - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hrms
    ports:
    - "3306:3306"
    volumes:
    - db_data:/var/lib/mysql

volumes:
  db_data: