# Generated by Django 5.2 on 2025-05-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_no", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
                ("department_id", models.IntegerField()),
                ("position_id", models.IntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("재직", "Active"), ("퇴사", "Resigned")],
                        max_length=10,
                    ),
                ),
                ("entry_date", models.DateField()),
                ("leave_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
