"""
Django settings for hrms_backend project.
Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path

# Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent

# ================================
# 🔐 Security Configuration
# ================================

SECRET_KEY = "django-insecure-ajtesfptr&nx3k6+053%n^ma(j)q2g*glky4r5di%_dezz7d%4"
DEBUG = True
ALLOWED_HOSTS = ["*"]  # Docker와 로컬 개발 환경에서 모든 호스트 접근 허용

# ================================
# 📦 Application Definition
# ================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",            # Django REST Framework
    "authentication",            # 인증 및 사용자 관리 앱
    "users",                     # 사용자 정보 관리 앱
    "departments",               # 부서 정보 관리 앱
    "attendance",                # 근태 관리 앱
    "leaves",                    # 휴가 관리 앱
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hrms_backend.urls"

# ================================
# 📂 Templates Configuration
# ================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hrms_backend.wsgi.application"

# ================================
# 🗄️ Database Configuration (MySQL)
# ================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'system_hrms',
        'USER': 'root',
        'PASSWORD': 'password',
        'HOST': 'db',
        'PORT': '3306',
    }
}

# ================================
# 🔐 Password Validation
# ================================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ================================
# 🌐 Internationalization
# ================================
LANGUAGE_CODE = "ko-kr"
TIME_ZONE = "Asia/Seoul"
USE_I18N = True
USE_TZ = False

# ================================
# 🖼️ Static Files (CSS, JavaScript, Images)
# ================================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

# ================================
# 🗃️ Default Primary Key Field Type
# ================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
